### PR TITLE
Change to using "domain" rather than "url"

### PR DESCRIPTION
**Pull request by nottrobin**
And document it in README

QA
--

``` bash
$ python3 -m venv env3
$ source env3/bin/activate
$ pip install -e .

$ upload-assets --api-domain assets.ubuntu.com some-file.png
$ upload-assets -d assets.ubuntu.com some-file.png
$ UPLOAD_ASSETS_API_DOMAIN=assets.ubuntu.com upload-assets some-file.png
```

### CODE REVIEW

**Comment by nottrobin** [comment]
Resolves #5.

**Comment by nottrobin** [comment]
[API updates to upload-assets](https://trello.com/c/3VSo9Hig/3082-api-updates-to-upload-assets)

**Comment by anthonydillon** [comment]
Following the QA steps im getting the following issue:
```bash
upload-assets --api-domain assets.ubuntu.com ~/Downloads/cloud-asset.svg 
usage: upload-assets [-h] [-d API_DOMAIN] [-i] -s API_TOKEN [-p URL_PATH]
                     [-t TAGS]
                     upload_paths [upload_paths ...]
upload-assets: error: the following arguments are required: -s/--api-token
```

**Review by anthonydillon — CHANGES_REQUESTED** [review]
Code looks good but hitting a QA issue.

**Comment by anthonydillon** [comment]
Confirming its not using the snap:
```bash
which upload-assets
/home/ant/Documents/Canonical/Git/asset-uploader/env3/bin/upload-assets
```

**Comment by nottrobin** [comment]
@anthonydillon that's expected - if you don't provide the key, it asks for it

**Comment by anthonydillon** [comment]
Oh i thought i had that as a environment variable. Forgot it changed. Will update. Thanks.

**Review by anthonydillon — APPROVED** [review]

**Pull request merged**
