### PR TITLE
Fix snap by basing off core18

### PR DESCRIPTION
**Pull request by nottrobin**
QA
--

``` bash
snapcraft clean
snapcraft
snap install --devmode upload-assets_0.2.1_amd64.snap
upload-assets --help
```

^ Check all commands succeed and help prints out properly

### CODE REVIEW

**Comment by deadlight** [comment]
@nottrobin when running `snapcraft`, I get:
```
Successfully downloaded pip
Collecting pip
Installing collected packages: pip
Successfully installed pip-19.1.1
Traceback (most recent call last):
  File "/home/deadlight/projects/upload-assets/parts/repo/install/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/deadlight/projects/upload-assets/parts/repo/install/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/deadlight/projects/upload-assets/parts/repo/install/lib/python3.6/site-packages/pip/__main__.py", line 16, in <module>
    from pip._internal import main as _main  # isort:skip # noqa
  File "/home/deadlight/projects/upload-assets/parts/repo/install/lib/python3.6/site-packages/pip/_internal/__init__.py", line 40, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/home/deadlight/projects/upload-assets/parts/repo/install/lib/python3.6/site-packages/pip/_internal/cli/autocompletion.py", line 8, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/home/deadlight/projects/upload-assets/parts/repo/install/lib/python3.6/site-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/home/deadlight/projects/upload-assets/parts/repo/install/lib/python3.6/site-packages/pip/_internal/cli/cmdoptions.py", line 14, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils.util'
Traceback (most recent call last):
  File "/home/deadlight/projects/upload-assets/parts/repo/install/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/deadlight/projects/upload-assets/parts/repo/install/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/deadlight/projects/upload-assets/parts/repo/install/lib/python3.6/site-packages/pip/__main__.py", line 16, in <module>
    from pip._internal import main as _main  # isort:skip # noqa
  File "/home/deadlight/projects/upload-assets/parts/repo/install/lib/python3.6/site-packages/pip/_internal/__init__.py", line 40, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/home/deadlight/projects/upload-assets/parts/repo/install/lib/python3.6/site-packages/pip/_internal/cli/autocompletion.py", line 8, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/home/deadlight/projects/upload-assets/parts/repo/install/lib/python3.6/site-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/home/deadlight/projects/upload-assets/parts/repo/install/lib/python3.6/site-packages/pip/_internal/cli/cmdoptions.py", line 14, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils.util'
Failed to run '/home/deadlight/projects/upload-assets/parts/repo/install/usr/bin/python3 -m pip list': Exited with code 1.
```

**Comment by nottrobin** [comment]
@deadlight show me `snapcraft --version`?

**Comment by deadlight** [comment]
@nottrobin `snapcraft, version 2.43.1+18.4`

**Comment by nottrobin** [comment]
@deadlight yeah I'm on `3.5`. try removing it and `snap install`ing it again?

**Comment by tbille** [comment]
```
$ snap install --devmode upload-assets_0.2.1_amd64.snap
upload-assets 0.2.1 installed

$ upload-assets --version
0.2.0
```

**Comment by nottrobin** [comment]
@tbille please file that as an issue which I'll try to address separately.

**Review by tbille — APPROVED** [review]

**Pull request merged**
