### PR TITLE
Add --version option

### PR DESCRIPTION
**Pull request by nottrobin**
Also tidy up a couple of things.

QA
--

``` bash
python3 -m venv env3
source env3/bin/activate
pip install -e .
upload-assets --version
upload-assets -v
```

### CODE REVIEW

**Comment by nottrobin** [comment]
Fixes #18

**Comment by nottrobin** [comment]
[API updates to upload-assets](https://trello.com/c/3VSo9Hig/3082-api-updates-to-upload-assets)

**Review by anthonydillon — CHANGES_REQUESTED** [review]
Doesn't work: env3/bin/upload-assets -v
usage: upload-assets [-h] [-u API_URL] -s API_TOKEN [-p URL_PATH] [-t TAGS]
                     [-v]
                     [upload_paths [upload_paths ...]]
upload-assets: error: the following arguments are required: -s/--api-token

**Comment by anthonydillon** [comment]
```bash
env3/bin/upload-assets -v
usage: upload-assets [-h] [-u API_URL] -s API_TOKEN [-p URL_PATH] [-t TAGS]
                     [-v]
                     [upload_paths [upload_paths ...]]
upload-assets: error: the following arguments are required: -s/--api-token
```

**Review by anthonydillon — APPROVED** [review]
Code and QA :+1:

**Pull request merged**
